// onboarding/writers/portals.mjs - copy templates/portals.example.yml
// into portals.yml, optionally injecting custom title_filter keywords
// and per-company enabled toggles.
//
// Strategy:
//   1. Read templates/portals.example.yml as the canonical source.
//   2. Parse with the yaml package, preserving comments where possible.
//   3. If use_defaults is true, pass the document through unchanged
//      EXCEPT for stripping any obvious smart-quote bug from the example
//      (one search_query in the example uses curly quotes that break
//      js-yaml's strict mode - we patch that defensively).
//   4. If use_defaults is false:
//      - title_filter.positive  <- payload.title_filter.positive (replace)
//      - title_filter.negative  <- payload.title_filter.negative (replace)
//      - For each tracked_companies entry, set enabled = payload.companies
//        toggle if a matching name is provided; otherwise leave default.
//   5. Atomic write to portals.yml.

import { readFile, writeFile, rename, unlink } from 'node:fs/promises';
import YAML from 'yaml';
import { buildPaths } from '../paths.mjs';

const activeWrites = new Map();

async function withFileMutex(filePath, fn) {
  const prev = activeWrites.get(filePath) ?? Promise.resolve();
  const next = prev.catch(() => {}).then(fn);
  activeWrites.set(filePath, next);
  try {
    return await next;
  } finally {
    if (activeWrites.get(filePath) === next) activeWrites.delete(filePath);
  }
}

async function atomicWrite(filePath, content) {
  const tmp = `${filePath}.tmp-${process.pid}-${Date.now()}`;
  try {
    await writeFile(tmp, content, 'utf-8');
    await rename(tmp, filePath);
  } catch (err) {
    try { await unlink(tmp); } catch { /* ignore */ }
    throw err;
  }
}

export class PortalsTemplateMissingError extends Error {
  constructor(message) {
    super(message);
    this.name = 'PortalsTemplateMissingError';
    this.code = 'PORTALS_TEMPLATE_MISSING';
  }
}

/**
 * Sanitize the example YAML for known issues:
 *   - The "Perplexity" entry uses U+2018/U+2019 smart quotes around its
 *     scan_query string, which the yaml parser tolerates but produces
 *     surprising results when re-serialized. We replace them with ASCII
 *     single quotes so the round-trip is clean.
 */
function sanitizeYamlSource(text) {
  return text.replace(/[‘’]/g, "'");
}

/**
 * Build portals.yml content from the template and the user's payload.
 * Pure - returns a string. The caller writes it.
 *
 * @param {string} templateText  contents of templates/portals.example.yml
 * @param {object} payload       already validated by portalsSchema
 * @returns {string}
 */
export function buildPortalsYaml(templateText, payload) {
  const sanitized = sanitizeYamlSource(templateText);
  const doc = YAML.parse(sanitized);
  if (!doc || typeof doc !== 'object') {
    throw new PortalsTemplateMissingError('portals template parsed to non-object');
  }

  if (!payload.use_defaults) {
    if (payload.title_filter) {
      if (Array.isArray(payload.title_filter.positive) && payload.title_filter.positive.length > 0) {
        doc.title_filter = doc.title_filter ?? {};
        doc.title_filter.positive = payload.title_filter.positive;
      }
      if (Array.isArray(payload.title_filter.negative) && payload.title_filter.negative.length > 0) {
        doc.title_filter = doc.title_filter ?? {};
        doc.title_filter.negative = payload.title_filter.negative;
      }
    }
    if (Array.isArray(payload.companies) && payload.companies.length > 0 && Array.isArray(doc.tracked_companies)) {
      const wanted = new Map(payload.companies.map((c) => [String(c.name).toLowerCase(), Boolean(c.enabled)]));
      for (const c of doc.tracked_companies) {
        if (!c || typeof c !== 'object' || !c.name) continue;
        const flag = wanted.get(String(c.name).toLowerCase());
        if (typeof flag === 'boolean') c.enabled = flag;
      }
    }
  }

  // Keep a slim header for provenance.
  const header = '# Portal Scanner Configuration\n# Generated by the dashboard onboarding flow. Edit freely.\n\n';
  return header + YAML.stringify(doc, { indent: 2, lineWidth: 0 });
}

/**
 * Write portals.yml from the template + payload.
 * @param {string} root
 * @param {object} payload  validated by portalsSchema
 * @returns {Promise<{path: string, bytes: number, writtenAt: number}>}
 */
export async function writePortalsYaml(root, payload) {
  const paths = buildPaths(root);
  let templateText;
  try {
    templateText = await readFile(paths.portalsTemplate, 'utf-8');
  } catch (err) {
    if (err.code === 'ENOENT') {
      throw new PortalsTemplateMissingError(
        `portals template not found at ${paths.portalsTemplate}`,
      );
    }
    throw err;
  }
  const yamlText = buildPortalsYaml(templateText, payload);
  return withFileMutex(paths.portalsYaml, async () => {
    await atomicWrite(paths.portalsYaml, yamlText);
    return { path: paths.portalsYaml, bytes: yamlText.length, writtenAt: Date.now() };
  });
}

// ---------------------------------------------------------------------------
// Validation block
// ---------------------------------------------------------------------------
if (import.meta.url === `file://${process.argv[1]}`) {
  const failures = [];
  let totalTests = 0;
  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  const { fileURLToPath } = await import('node:url');
  const tmpRoot = `/tmp/onboarding-portals-validate-${Date.now()}`;
  await fs.mkdir(path.join(tmpRoot, 'templates'), { recursive: true });

  // Resolve the real template relative to this script (project root is 4 levels up
  // from web-dashboard/server/onboarding/writers/).
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const realTemplate = path.resolve(__dirname, '..', '..', '..', '..', 'templates', 'portals.example.yml');
  const tmpl = await fs.readFile(realTemplate, 'utf-8');
  await fs.writeFile(path.join(tmpRoot, 'templates', 'portals.example.yml'), tmpl);

  // Test 1: use_defaults preserves the original tracked_companies count.
  totalTests += 1;
  try {
    const r = await writePortalsYaml(tmpRoot, { use_defaults: true });
    const onDisk = await fs.readFile(r.path, 'utf-8');
    const parsed = YAML.parse(onDisk);
    if (!Array.isArray(parsed.tracked_companies) || parsed.tracked_companies.length === 0) {
      failures.push('use_defaults: tracked_companies missing');
    }
  } catch (err) {
    failures.push(`use_defaults threw: ${err.message}`);
  }

  // Test 2: custom title_filter overwrites positive list.
  totalTests += 1;
  try {
    const r = await writePortalsYaml(tmpRoot, {
      use_defaults: false,
      title_filter: { positive: ['Backend Engineer', 'Platform Engineer'], negative: ['Junior'] },
      companies: [],
    });
    const parsed = YAML.parse(await fs.readFile(r.path, 'utf-8'));
    if (parsed.title_filter.positive[0] !== 'Backend Engineer') failures.push('title_filter not applied');
    if (parsed.title_filter.negative[0] !== 'Junior') failures.push('negative not applied');
  } catch (err) {
    failures.push(`custom title_filter threw: ${err.message}`);
  }

  // Test 3: company toggles flip enabled flags.
  totalTests += 1;
  try {
    const r = await writePortalsYaml(tmpRoot, {
      use_defaults: false,
      companies: [{ name: 'Anthropic', enabled: false }, { name: 'OpenAI', enabled: false }],
    });
    const parsed = YAML.parse(await fs.readFile(r.path, 'utf-8'));
    const anthropic = parsed.tracked_companies.find((c) => c.name === 'Anthropic');
    const openai = parsed.tracked_companies.find((c) => c.name === 'OpenAI');
    if (!anthropic || anthropic.enabled !== false) failures.push('Anthropic enabled flag not flipped');
    if (!openai || openai.enabled !== false) failures.push('OpenAI enabled flag not flipped');
  } catch (err) {
    failures.push(`company toggles threw: ${err.message}`);
  }

  await fs.rm(tmpRoot, { recursive: true, force: true });

  if (failures.length > 0) {
    console.error(`VALIDATION FAILED - ${failures.length} of ${totalTests} tests failed:`);
    for (const f of failures) console.error(`  - ${f}`);
    process.exit(1);
  } else {
    console.log(`VALIDATION PASSED - All ${totalTests} tests produced expected results`);
    process.exit(0);
  }
}
