// onboarding/writers/profile.mjs - serialize and atomically write
// config/profile.yml from a zod-validated payload.
//
// The output structure matches config/profile.example.yml exactly. Only
// fields that are present in the payload are emitted - we don't write
// commented-out optional sections like the example does, because the
// onboarding modal owns the canonical fields and any future edits should
// happen via the modal's "edit profile" path or by hand-editing the file.
//
// Atomic: write .tmp-<pid>-<ts>, rename. mkdir parents.

import { writeFile, rename, mkdir, unlink } from 'node:fs/promises';
import path from 'node:path';
import YAML from 'yaml';
import { buildPaths } from '../paths.mjs';

const activeWrites = new Map();

async function withFileMutex(filePath, fn) {
  const prev = activeWrites.get(filePath) ?? Promise.resolve();
  const next = prev.catch(() => {}).then(fn);
  activeWrites.set(filePath, next);
  try {
    return await next;
  } finally {
    if (activeWrites.get(filePath) === next) activeWrites.delete(filePath);
  }
}

async function atomicWrite(filePath, content) {
  const tmp = `${filePath}.tmp-${process.pid}-${Date.now()}`;
  try {
    await writeFile(tmp, content, 'utf-8');
    await rename(tmp, filePath);
  } catch (err) {
    try { await unlink(tmp); } catch { /* ignore */ }
    throw err;
  }
}

/**
 * Strip undefined / empty-optional keys so the YAML is clean. We KEEP
 * empty-string defaults like '' for required-ish fields but drop them if
 * the value is the empty string AND the key is in the optional set.
 */
function compact(obj, optionalKeys = new Set()) {
  if (obj == null || typeof obj !== 'object' || Array.isArray(obj)) return obj;
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v === undefined) continue;
    if (optionalKeys.has(k) && v === '') continue;
    out[k] = v;
  }
  return out;
}

/**
 * Serialize a validated profile payload into YAML.
 * Public-ish so writers/profile-md.mjs can also load fresh data.
 */
export function serializeProfileYaml(payload) {
  const candidate = compact(
    payload.candidate,
    new Set(['phone', 'linkedin', 'portfolio_url', 'github', 'twitter', 'canva_resume_design_id']),
  );
  const compensation = compact(
    payload.compensation,
    new Set(['location_flexibility']),
  );
  const location = compact(
    payload.location,
    new Set(['visa_status', 'onsite_availability']),
  );
  const narrative = compact(payload.narrative, new Set([]));

  // Drop empty proof_points entirely if it's an empty array.
  if (Array.isArray(narrative.proof_points) && narrative.proof_points.length === 0) {
    delete narrative.proof_points;
  }

  // Drop the dashboard block when both fields are blank to avoid
  // emitting an empty `dashboard:` mapping.
  if (narrative.dashboard && typeof narrative.dashboard === 'object') {
    const dash = narrative.dashboard;
    if (!dash.url && !dash.password) {
      delete narrative.dashboard;
    }
  }

  const doc = {
    candidate,
    target_roles: payload.target_roles,
    narrative,
    compensation,
    location,
  };

  // Optional: location_filter block (added 2026-04). Only emit when present so
  // existing profiles without a filter remain byte-stable on save.
  if (payload.location_filter && typeof payload.location_filter === 'object') {
    doc.location_filter = payload.location_filter;
  }

  // Header comment so the file is identifiable on hand inspection.
  const header = '# Faber Profile Configuration\n# Generated by the dashboard onboarding flow. Edit freely.\n\n';
  return header + YAML.stringify(doc, { indent: 2, lineWidth: 0 });
}

/**
 * Write profile.yml atomically.
 * @param {string} root
 * @param {object} payload  already validated by profileYamlSchema
 * @returns {Promise<{path: string, bytes: number, writtenAt: number}>}
 */
export async function writeProfileYaml(root, payload) {
  const paths = buildPaths(root);
  await mkdir(paths.configDir, { recursive: true });
  const yamlText = serializeProfileYaml(payload);
  return withFileMutex(paths.profileYaml, async () => {
    await atomicWrite(paths.profileYaml, yamlText);
    return { path: paths.profileYaml, bytes: yamlText.length, writtenAt: Date.now() };
  });
}

// ---------------------------------------------------------------------------
// Validation block
// ---------------------------------------------------------------------------
if (import.meta.url === `file://${process.argv[1]}`) {
  const failures = [];
  let totalTests = 0;
  const fs = await import('node:fs/promises');
  const tmpRoot = `/tmp/onboarding-profile-validate-${Date.now()}`;
  await fs.mkdir(tmpRoot, { recursive: true });

  const payload = {
    candidate: {
      full_name: 'Jane Doe',
      email: 'jane@example.com',
      phone: '+1-555-0123',
      location: 'NYC',
      linkedin: 'linkedin.com/in/janedoe',
      portfolio_url: '',
      github: 'github.com/janedoe',
      twitter: '',
    },
    target_roles: {
      primary: ['Senior PM'],
      archetypes: [{ name: 'PM', level: 'Senior', fit: 'primary' }],
    },
    narrative: {
      headline: 'h',
      exit_story: 'e',
      superpowers: ['a', 'b', 'c'],
      proof_points: [],
    },
    compensation: {
      target_range: '$150K',
      currency: 'USD',
      minimum: '$120K',
      location_flexibility: '',
    },
    location: {
      country: 'US',
      city: 'NYC',
      timezone: 'EST',
      visa_status: '',
    },
  };

  // Test 1: writeProfileYaml writes valid YAML.
  totalTests += 1;
  try {
    const r = await writeProfileYaml(tmpRoot, payload);
    const text = await fs.readFile(r.path, 'utf-8');
    if (!text.includes('full_name: Jane Doe')) failures.push('YAML missing full_name');
    if (text.includes('twitter:')) failures.push('YAML should drop empty twitter');
    if (text.includes('proof_points')) failures.push('YAML should drop empty proof_points');
  } catch (err) {
    failures.push(`writeProfileYaml threw: ${err.message}`);
  }

  // Test 2: round-trip the YAML cleanly.
  totalTests += 1;
  try {
    const text = await fs.readFile(path.join(tmpRoot, 'config', 'profile.yml'), 'utf-8');
    const parsed = YAML.parse(text);
    if (parsed.candidate.email !== 'jane@example.com') failures.push('round-trip lost email');
    if (parsed.target_roles.archetypes[0].fit !== 'primary') failures.push('round-trip lost fit');
  } catch (err) {
    failures.push(`round-trip threw: ${err.message}`);
  }

  await fs.rm(tmpRoot, { recursive: true, force: true });

  if (failures.length > 0) {
    console.error(`VALIDATION FAILED - ${failures.length} of ${totalTests} tests failed:`);
    for (const f of failures) console.error(`  - ${f}`);
    process.exit(1);
  } else {
    console.log(`VALIDATION PASSED - All ${totalTests} tests produced expected results`);
    process.exit(0);
  }
}
