// onboarding/writers/profile-md.mjs - render modes/_profile.md from a
// structured payload + the canonical template.
//
// We do NOT do raw text substitution into modes/_profile.template.md because
// the template is HTML-comment-heavy and the user's structured payload
// doesn't map 1:1 to its narrative prose. Instead the template is a stable
// reference; this renderer composes the final markdown from sections we
// own. The output structure mirrors the template's section order so a
// returning user reads the same headings.
//
// Hard rule: every user-controlled string must flow through escapeForMarkdown
// before interpolation. The renderer treats that as a load-bearing invariant.

import { writeFile, rename, mkdir, unlink } from 'node:fs/promises';
import { buildPaths } from '../paths.mjs';
import { escapeForMarkdown } from '../validation.mjs';

const activeWrites = new Map();

async function withFileMutex(filePath, fn) {
  const prev = activeWrites.get(filePath) ?? Promise.resolve();
  const next = prev.catch(() => {}).then(fn);
  activeWrites.set(filePath, next);
  try {
    return await next;
  } finally {
    if (activeWrites.get(filePath) === next) activeWrites.delete(filePath);
  }
}

async function atomicWrite(filePath, content) {
  const tmp = `${filePath}.tmp-${process.pid}-${Date.now()}`;
  try {
    await writeFile(tmp, content, 'utf-8');
    await rename(tmp, filePath);
  } catch (err) {
    try { await unlink(tmp); } catch { /* ignore */ }
    throw err;
  }
}

/** Map a 1-5 score to a verbal label so the table reads naturally. */
const LOCATION_LABELS = {
  remote_within_country:   'Remote within your country',
  remote_outside_country:  'Remote outside your country (different timezone)',
  hybrid_within_metro:     'Hybrid within your metro',
  onsite_within_metro:     'On-site within your metro',
  onsite_relocation:       'On-site requires relocation',
};

/**
 * Render a profile-md payload into a markdown string. Pure - no side effects.
 *
 * @param {object} payload  already validated by profileMdSchema
 * @returns {string}
 */
export function renderProfileMd(payload) {
  const archetypeRows = payload.archetypes.map((a) => {
    const name = escapeForMarkdown(a.name, { maxLen: 120 });
    const axes = a.axes.map((x) => escapeForMarkdown(x, { maxLen: 80 })).join(', ');
    const what = escapeForMarkdown(a.whatTheyBuy, { maxLen: 280 });
    const fit  = escapeForMarkdown(a.fit, { maxLen: 20 });
    return `| **${name}** | ${axes} | ${what} | _${fit}_ |`;
  }).join('\n');

  const locationRows = Object.entries(LOCATION_LABELS).map(([k, label]) => {
    const score = payload.location_scoring[k];
    return `| ${label} | **${score}** |`;
  }).join('\n');

  const dealBreakers = payload.deal_breakers.length === 0
    ? '_No specific deal-breakers listed._'
    : payload.deal_breakers.map((d) => `- ${escapeForMarkdown(d, { maxLen: 240 })}`).join('\n');

  const exit = escapeForMarkdown(payload.exit_narrative, { maxLen: 2400 });
  const advantage = escapeForMarkdown(payload.cross_cutting_advantage, { maxLen: 1200 });
  const compNotes = escapeForMarkdown(payload.comp_notes ?? '', { maxLen: 1200 });

  const portfolioBlock = (() => {
    if (!payload.portfolio || (!payload.portfolio.url && !payload.portfolio.password && !payload.portfolio.when_to_share)) {
      return '_No public portfolio configured. Add one anytime by editing this file._';
    }
    const lines = [];
    if (payload.portfolio.url) lines.push(`- **URL:** ${escapeForMarkdown(payload.portfolio.url, { maxLen: 300 })}`);
    if (payload.portfolio.password) lines.push(`- **Password:** ${escapeForMarkdown(payload.portfolio.password, { maxLen: 120 })}`);
    if (payload.portfolio.when_to_share) lines.push(`- **When to share:** ${escapeForMarkdown(payload.portfolio.when_to_share, { maxLen: 280 })}`);
    return lines.join('\n');
  })();

  return `# User Profile Context -- faber

<!-- ============================================================
     THIS FILE IS YOURS. It will NEVER be auto-updated.

     Generated by the dashboard onboarding flow. Edit freely.
     The system reads _shared.md (updatable) first, then this
     file (your overrides). Your customizations always win.
     ============================================================ -->

## Your Target Roles

| Archetype | Thematic axes | What they buy | Fit |
|-----------|---------------|---------------|-----|
${archetypeRows}

## Your Adaptive Framing

For every archetype above, when a JD matches it, emphasize the proof points
from \`cv.md\` and \`article-digest.md\` that align with the listed thematic
axes. The evaluation system uses this mapping to choose which stories to lead
with in tailored outputs.

## Your Exit Narrative

${exit}

## Your Cross-cutting Advantage

${advantage}

## Your Portfolio / Demo

${portfolioBlock}

## Your Comp Targets

${compNotes || '_See \`config/profile.yml\` for the canonical comp ranges. Adjust per opportunity._'}

## Your Negotiation Scripts

**Salary expectations:**
> "Based on market data for this role, I'm targeting [RANGE from profile.yml]. I'm flexible on structure -- what matters is the total package and the opportunity."

**Geographic discount pushback:**
> "The roles I'm competitive for are output-based, not location-based. My track record doesn't change based on postal code."

**When offered below target:**
> "I'm comparing with opportunities in the [higher range]. I'm drawn to [company] because of [reason]. Can we explore [target]?"

## Your Location Policy

| Scenario | Score (1-5) |
|----------|-------------|
${locationRows}

## Your Deal-Breakers

${dealBreakers}
`;
}

/**
 * Atomically write modes/_profile.md.
 * @param {string} root
 * @param {object} payload  already validated by profileMdSchema
 * @returns {Promise<{path: string, bytes: number, writtenAt: number}>}
 */
export async function renderAndWriteProfileMd(root, payload) {
  const paths = buildPaths(root);
  await mkdir(paths.modesDir, { recursive: true });
  const md = renderProfileMd(payload);
  return withFileMutex(paths.profileMd, async () => {
    await atomicWrite(paths.profileMd, md);
    return { path: paths.profileMd, bytes: md.length, writtenAt: Date.now() };
  });
}

// ---------------------------------------------------------------------------
// Validation block
// ---------------------------------------------------------------------------
if (import.meta.url === `file://${process.argv[1]}`) {
  const failures = [];
  let totalTests = 0;
  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  const tmpRoot = `/tmp/onboarding-profile-md-validate-${Date.now()}`;
  await fs.mkdir(tmpRoot, { recursive: true });

  const goodPayload = {
    archetypes: [
      { name: 'Senior PM', axes: ['agentic', 'platform'], whatTheyBuy: 'AI product leadership', fit: 'primary' },
      { name: 'Forward Deployed Engineer', axes: ['client-facing', 'fast delivery'], whatTheyBuy: 'AI deployment specialist', fit: 'secondary' },
    ],
    exit_narrative: 'I shipped Disney+ messaging to 250M+ subs. Now applying that scale to AI products.',
    cross_cutting_advantage: 'Technical builder with operating-income proof.',
    deal_breakers: ['No on-site 5d/wk', 'No mainframes'],
    location_scoring: {
      remote_within_country: 5,
      remote_outside_country: 4,
      hybrid_within_metro: 2,
      onsite_within_metro: 1,
      onsite_relocation: 1,
    },
    portfolio: { url: 'https://example.dev', password: '', when_to_share: 'Platform roles' },
    comp_notes: '',
  };

  // Test 1: render produces all required sections.
  totalTests += 1;
  const md = renderProfileMd(goodPayload);
  for (const heading of [
    '# User Profile Context -- faber',
    '## Your Target Roles',
    '## Your Adaptive Framing',
    '## Your Exit Narrative',
    '## Your Cross-cutting Advantage',
    '## Your Portfolio / Demo',
    '## Your Comp Targets',
    '## Your Negotiation Scripts',
    '## Your Location Policy',
    '## Your Deal-Breakers',
  ]) {
    if (!md.includes(heading)) failures.push(`render missing heading: ${heading}`);
  }

  // Test 2: archetype interpolation includes the names.
  totalTests += 1;
  if (!md.includes('**Senior PM**')) failures.push('render missing archetype name');
  if (!md.includes('**Forward Deployed Engineer**')) failures.push('render missing 2nd archetype');

  // Test 3: location scores rendered.
  totalTests += 1;
  if (!md.includes('Remote within your country | **5**')) failures.push('location score 5 missing');
  if (!md.includes('On-site requires relocation | **1**')) failures.push('location score 1 missing');

  // Test 4: escapeForMarkdown applied (HTML stripped, pipes escaped).
  totalTests += 1;
  const adversarial = {
    ...goodPayload,
    archetypes: [
      {
        name: 'Senior <script>alert(1)</script> PM',
        axes: ['axis | with pipe'],
        whatTheyBuy: '```bad\ncode\n```',
        fit: 'primary',
      },
    ],
  };
  const advMd = renderProfileMd(adversarial);
  if (advMd.includes('<script>')) failures.push('escape did not strip HTML in archetype');
  if (advMd.includes('axis | with pipe')) failures.push('escape did not escape pipe in axes');
  if (/^```/m.test(advMd) && !advMd.includes('`​`​`')) failures.push('escape did not neutralize fence in archetype');

  // Test 5: write to disk works.
  totalTests += 1;
  try {
    const r = await renderAndWriteProfileMd(tmpRoot, goodPayload);
    const onDisk = await fs.readFile(path.join(tmpRoot, 'modes', '_profile.md'), 'utf-8');
    if (!onDisk.includes('# User Profile Context -- faber')) failures.push('disk content missing top heading');
    void r;
  } catch (err) {
    failures.push(`renderAndWriteProfileMd threw: ${err.message}`);
  }

  await fs.rm(tmpRoot, { recursive: true, force: true });

  if (failures.length > 0) {
    console.error(`VALIDATION FAILED - ${failures.length} of ${totalTests} tests failed:`);
    for (const f of failures) console.error(`  - ${f}`);
    process.exit(1);
  } else {
    console.log(`VALIDATION PASSED - All ${totalTests} tests produced expected results`);
    process.exit(0);
  }
}
