// onboarding/writers/skip.mjs - one-shot skip-onboarding writer.
//
// Lets a user bypass the modal entirely by stubbing every required user-layer
// file with a sensible default. After skip:
//   - cv.md         a placeholder template the user can edit
//   - profile.yml   verbatim copy of config/profile.example.yml
//   - _profile.md   verbatim copy of modes/_profile.template.md
//   - portals.yml   verbatim copy of templates/portals.example.yml
//   - applications.md   empty tracker header
//
// All writes go through the same `.tmp-<pid>-<ts>` + rename pattern as the
// other writers; existing files are NEVER overwritten — they're skipped with
// `created: false` so a partial onboarding doesn't lose user data.
//
// The expected pattern: a fresh user clicks "skip onboarding" before they've
// touched anything. They get a working dashboard immediately and edit at
// their own pace via Settings (Cmd+,).

import { writeFile, rename, mkdir, copyFile, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

import { buildPaths } from '../paths.mjs';

const CV_STUB = `# Your Name

City, Country | you@example.com | (000) 000-0000

---

## CORE SKILLS

**Edit me:** open Settings (⌘,) and replace this with your real skills.

---

## PROFESSIONAL EXPERIENCE

### Role | Company | Location
**Start – End**

- Edit me: describe a deliverable, with a measurable outcome.

---

## EDUCATION

**Degree** | Institution | Year
`;

const TRACKER_HEADER = `# Applications Tracker

| # | Date | Company | Role | Score | Status | PDF | Report | Notes |
|---|------|---------|------|-------|--------|-----|--------|-------|
`;

async function fileExists(p) {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

async function atomicWriteIfMissing(target, content) {
  if (existsSync(target)) return false;
  await mkdir(path.dirname(target), { recursive: true });
  const tmp = `${target}.tmp-${process.pid}-${Date.now()}`;
  await writeFile(tmp, content, 'utf-8');
  await rename(tmp, target);
  return true;
}

async function copyIfMissing(source, target) {
  if (existsSync(target)) return false;
  if (!existsSync(source)) return false;
  await mkdir(path.dirname(target), { recursive: true });
  // copyFile is atomic on POSIX-ish filesystems; matches the other writers'
  // expectations and is simpler than read-then-write for an unmodified copy.
  const tmp = `${target}.tmp-${process.pid}-${Date.now()}`;
  await copyFile(source, tmp);
  await rename(tmp, target);
  return true;
}

/**
 * Skip the onboarding modal entirely. Writes every required user-layer file
 * with sensible defaults; never overwrites a file that already exists.
 *
 * @param {string} root - absolute careerOpsRoot
 * @returns {Promise<{
 *   created: Record<string, boolean>,
 *   skipped: string[],
 *   path: string,
 * }>}
 */
export async function skipOnboarding(root) {
  const paths = buildPaths(root);
  const created = {
    cv: false,
    profile: false,
    profileMd: false,
    portals: false,
    tracker: false,
  };
  const skipped = [];

  // 1. CV placeholder
  if (!(await fileExists(paths.cv))) {
    created.cv = await atomicWriteIfMissing(paths.cv, CV_STUB);
  } else {
    skipped.push('cv.md');
  }

  // 2. Profile from example. The example IS valid YAML and has every key.
  if (!(await fileExists(paths.profileYaml))) {
    created.profile = await copyIfMissing(paths.profileExample, paths.profileYaml);
    if (!created.profile) {
      // example missing — fall back to a minimal handcrafted skeleton so the
      // dashboard still boots. The Settings/Profile pane can fill the rest.
      created.profile = await atomicWriteIfMissing(
        paths.profileYaml,
        `# Faber profile - generated by skip-onboarding\n# Edit in the dashboard via Cmd+,\n\ncandidate:\n  full_name: ""\n  email: ""\n  location: ""\ntarget_roles:\n  primary: []\nnarrative: {}\ncompensation:\n  target_range: ""\n  currency: USD\n  minimum: ""\nlocation:\n  country: ""\n  city: ""\n  timezone: ""\n`,
      );
    }
  } else {
    skipped.push('config/profile.yml');
  }

  // 3. Profile.md from template
  if (!(await fileExists(paths.profileMd))) {
    created.profileMd = await copyIfMissing(paths.profileMdTemplate, paths.profileMd);
  } else {
    skipped.push('modes/_profile.md');
  }

  // 4. Portals from example
  if (!(await fileExists(paths.portalsYaml))) {
    created.portals = await copyIfMissing(paths.portalsTemplate, paths.portalsYaml);
  } else {
    skipped.push('portals.yml');
  }

  // 5. Tracker header
  if (!(await fileExists(paths.applicationsMd))) {
    created.tracker = await atomicWriteIfMissing(paths.applicationsMd, TRACKER_HEADER);
  } else {
    skipped.push('data/applications.md');
  }

  return { created, skipped, path: paths.root };
}

// -- Self-test --------------------------------------------------------------
if (import.meta.url === `file://${process.argv[1]}`) {
  const { rmSync, mkdirSync, writeFileSync } = await import('node:fs');
  const tmp = path.join('/tmp', `skip-test-${process.pid}`);
  rmSync(tmp, { recursive: true, force: true });
  mkdirSync(tmp, { recursive: true });
  mkdirSync(path.join(tmp, 'config'), { recursive: true });
  mkdirSync(path.join(tmp, 'modes'), { recursive: true });
  mkdirSync(path.join(tmp, 'templates'), { recursive: true });
  // seed the source templates
  writeFileSync(path.join(tmp, 'config', 'profile.example.yml'), 'candidate: {}\n');
  writeFileSync(path.join(tmp, 'modes', '_profile.template.md'), '# template\n');
  writeFileSync(path.join(tmp, 'templates', 'portals.example.yml'), 'tracked_companies: []\n');

  const failures = [];
  const r = await skipOnboarding(tmp);
  if (!r.created.cv) failures.push('cv was not created');
  if (!r.created.profile) failures.push('profile was not created');
  if (!r.created.profileMd) failures.push('profileMd was not created');
  if (!r.created.portals) failures.push('portals was not created');
  if (!r.created.tracker) failures.push('tracker was not created');
  if (r.skipped.length !== 0) failures.push(`unexpected skipped: ${r.skipped.join(',')}`);

  // Run again — everything should be skipped (no overwrite of existing files)
  const r2 = await skipOnboarding(tmp);
  if (r2.skipped.length !== 5) {
    failures.push(`second pass should skip all 5; got ${r2.skipped.length}`);
  }

  rmSync(tmp, { recursive: true, force: true });

  if (failures.length) {
    console.error(`FAIL: ${failures.length} of 7 checks failed`);
    failures.forEach((f) => console.error(`  - ${f}`));
    process.exit(1);
  } else {
    console.log('OK: skipOnboarding writes 5 files on first run, skips on second');
    process.exit(0);
  }
}
